version: '3'

services:
  phpbb:
    image: phpbb
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: phpbb
    restart: unless-stopped
    ports:
      - "6862:80"
    depends_on:
      - db
    environment:
      - MSMTP_FROM=${MSMTP_FROM}
      - MSMTP_USER=${MSMTP_USER}
      - MSMTP_PASSWORD=${MSMTP_PASSWORD}
      - MSMTP_HOST=${MSMTP_HOST}
      - MSMTP_PORT=${MSMTP_PORT}
      - MSMTP_TLS=${MSMTP_TLS}
      - MSMTP_TLS_TRUST_FILE=${MSMTP_TLS_TRUST_FILE}
      - PHPBB_DB_HOST=db
      - PHPBB_DB_NAME=${MYSQL_DATABASE}
      - PHPBB_DB_USER=${MYSQL_USER}
      - PHPBB_DB_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./phpbb:/var/www/html/phpbb

  db:
    image: mariadb:latest
    container_name: phpbb_db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    volumes:
      - ./db:/var/lib/mysql
